### ISSUE TITLE
Razer Blade Stealth logo activation

### ISSUE THREAD

**Issue by xlinbsd** [lah7/polychromatic#104] opened 2017-07-14 10:21 UTC
Can you please add the option to activate/deactivate the Razer logo of the shell from your interface, since the driver can do it ?

**Comment by lah7** [comment] 2017-07-15 19:14
Since I don't have the hardware to know which function provides this, please could you run this command and paste me the capabilities the daemon outputs for this device?

    polychromatic-controller --print-device-info

**Comment by xlinbsd** [comment] 2017-07-15 19:25
Hello,

Here is the daemon doc that is working.
https://github.com/lah7/polychromatic/issues/104#issuecomment-315555749

The command returns:
```
# Device Info
Name: Razer Blade Stealth (Late 2016)
Type: keyboard
 
# Device Capabilities
{'lighting_logo_pulsate': False, 'lighting_logo_blinking': False, 'type': True, 'lighting_breath_dual': True, 'lighting_scroll_none': False, 'firmware_version': True, 'lighting_led_single': False, 'lighting_logo_active': False, 'macro_mode_led_effect': False, 'lighting_logo_reactive': False, 'macro_logic': False, 'lighting_scroll_pulsate': False, 'game_mode_led': False, 'lighting_logo': False, 'lighting_scroll_brightness': False, 'lighting_scroll_static': False, 'name': True, 'lighting_backlight': False, 'lighting': True, 'brightness': True, 'lighting_scroll_breath_random': False, 'lighting_reactive': True, 'lighting_logo_brightness': False, 'lighting_scroll': False, 'lighting_breath_random': True, 'lighting_scroll_blinking': False, 'lighting_scroll_spectrum': False, 'lighting_breath_single': True, 'lighting_led_matrix': True, 'lighting_ripple_random': True, 'macro_tartarus_mode_modifier': False, 'lighting_ripple': True, 'lighting_spectrum': True, 'lighting_logo_static': False, 'lighting_scroll_reactive': False, 'lighting_logo_none': False, 'lighting_static': True, 'lighting_scroll_breath_single': False, 'lighting_none': True, 'lighting_backlight_active': False, 'lighting_pulsate': False, 'lighting_scroll_breath_dual': False, 'lighting_logo_breath_random': False, 'lighting_scroll_active': False, 'lighting_wave': True, 'lighting_breath_triple': False, 'lighting_logo_breath_single': False, 'lighting_logo_breath_dual': False, 'serial': True, 'lighting_logo_spectrum': False, 'macro_mode_led': False}
```

**Comment by lah7** [comment] 2017-07-15 20:24
Thanks for that, I've discovered from @terrycain that the **Blade** has a `lighting_logo` which can toggle this on/off independently, but the **Blade Stealth** does not (it's part of the matrix). This just means that if you were to toggle the logo, the rest of the keyboard would go blank.

So, to check that's the case, please could you [run this `step-through-matrix.py` script](https://raw.githubusercontent.com/lah7/polychromatic/master/tools/step-through-matrix.py), note each key that lights up and paste the results here.

**Comment by xlinbsd** [comment] 2017-07-15 20:44
I'm not sure, since I use my RBS (kabylake 2016) with the logo light off (my setting) but the keyboard with light on everydays.

Here is the result of the matric parsing (french azerty hardware), the logo does not light up in the process. The matrix follows exactly all the keyboard in the reading order.
```
X, Y    Label
0, 0 = 
0, 1 = esc
0, 2 = F1
0, 3 = F2
0, 4 = F3
0, 5 = F4
0, 6 = F5
0, 7 = F6       
0, 8 = F7
0, 9 = F8
0, 10 = F9
0, 11 = F10
0, 12 = F11
0, 13 = F12
0, 14 = insert
0, 15 = delete
1, 0 = 
1, 1 = square
1, 2 = 1
1, 3 = 2
1, 4 = 3
1, 5 = 4
1, 6 = 5
1, 7 = 6
1, 8 = 7
1, 9 = 8
1, 10 = 9
1, 11 = 0
1, 12 = °
1, 13 = =
1, 14 = 
1, 15 = backspace
2, 0 = 
2, 1 = tab
2, 2 = a
2, 3 = z
2, 4 = e
2, 5 = r
2, 6 = t
2, 7 = y
2, 8 = u
2, 9 = i
2, 10 = o
2, 11 = p
2, 12 = ^
2, 13 = $
2, 14 = 
2, 15 = 
3, 0 = 
3, 1 = capslock
3, 2 = q
3, 3 = s
3, 4 = d
3, 5 = f
3, 6 = g
3, 7 = h
3, 8 = j
3, 9 = k
3, 10 = l
3, 11 = m
3, 12 = ù
3, 13 = *
3, 14 = 
3, 15 = enter
4, 0 = 
4, 1 = cap
4, 2 = <
4, 3 = w
4, 4 = x
4, 5 = c
4, 6 = v
4, 7 = b
4, 8 = n
4, 9 = ,
4, 10 = ;
4, 11 = :
4, 12 = !
4, 13 = 
4, 14 = 
4, 15 = rightcap
5, 0 = 
5, 1 = leftctrl 
5, 2 = func
5, 3 = super
5, 4 = alt
5, 5 = 
5, 6 = 
5, 7 = 
5, 8 = 
5, 9 = altgr
5, 10 = rightfunc
5, 11 = rigthctrl
5, 12 = left
5, 13 = up
5, 14 = down
5, 15 = right
```

**Comment by lah7** [comment] 2017-07-15 21:11
Hmm, I'm now unsure how lighting works on your device. I was thinking it was like some devices (like BlackWidow keyboards) where the logo LED is part of the matrix. :confused: 

At the moment, it's looking like the daemon doesn't expose any function for Polychromatic to use for toggling the logo.

How do you toggle the logo? Do you run a command to the driver directly?

**Comment by xlinbsd** [comment] 2017-07-15 21:12
https://github.com/terrycain/razer-drivers/wiki/Using-the-keyboard-driver#logo_led_state---sets-the-onoff-state-of-the-blade-stealth-lid-logo-write-only

**Comment by lah7** [comment] 2017-07-16 10:22
Okay, I got some info from @terrycain (who writes the driver/daemon), the daemon is just missing this option. He's aware of what needs to be done.

**Comment by lah7** [comment] 2017-07-16 21:03
**Fixed** -- it'll be available in the next daemon update, or right now by [downloading that revised file](https://raw.githubusercontent.com/terrycain/razer-drivers/dd7617aa4edfd07400d5b6331cdbee11f4bf8f8b/daemon/razer_daemon/hardware/keyboards.py) and replace `/usr/lib/python3/dist-packages/razer_daemon/hardware/keyboards.py`.

With a bit of luck, the logo toggle should appear. :ok_hand:

**Comment by xlinbsd** [comment] 2017-07-17 13:26
With this update, Polychromatic Controller is broken for the PC settings.

- Lightning Effects are gone.
- Key Modes are gone
- Brightness slider is replaced by a switch, probably for the logo, but generating some system error.

I rolled back my keyboard.py file
(I tried to send you screenshot but github can't process my pngs and jpgs)

**Comment by lah7** [comment] 2017-07-17 17:22
A screenshot would definitely be handy. You could try running from the terminal, which will reveal the exception thrown:

    polychromatic-controller -v

But it could actually be because there are other changes in that file that caused it to break. That suggestion was just a "dirty" trick. The next daemon update might be OK.

Alternately, see what the output of this is again, the capabilities should be updated:

    polychromatic-controller --print-device-info

**Comment by xlinbsd** [comment] 2017-07-19 09:01
http://artivisme.org/razer_before.png
http://artivisme.org/razer_after.png

**Comment by xlinbsd** [comment] 2017-07-19 09:04
The exception thrown
```
 ** Device state recalled: [Serial: BY1641A28000456] [Source: logo] [State: effect] [No value]
 ** Device state recalled: [Serial: BY1641A28000456] [Source: logo] [State: colour_primary] [No value]
 ** Device state recalled: [Serial: BY1641A28000456] [Source: main] [State: profile] [No value]
Selected: Razer Blade Stealth (Late 2016) [BY1641A28000456]

Set active device: Razer Blade Stealth (Late 2016)
 ** Device state recalled: [Serial: BY1641A28000456] [Source: logo] [State: colour_primary] [No value]
Device supports 'brightness'
Device supports 'lighting_logo_active'
Traceback (most recent call last):
  File "/usr/bin/polychromatic-controller", line 170, in title_changed_cb
    app.process_command(title)
  File "/usr/bin/polychromatic-controller", line 1161, in process_command
    self.update_device_active_options()
  File "/usr/bin/polychromatic-controller", line 1584, in update_device_active_options
    if self.active_device.fx.misc.logo.active == 1:
  File "/usr/lib/python3/dist-packages/razer/client/fx.py", line 513, in active
    return func()
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 654, in _message_cb
    (candidate_method, parent_method) = _method_lookup(self, method_name, interface_name)
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 246, in _method_lookup
    raise UnknownMethodException('%s is not a valid method of interface %s' % (method_name, dbus_interface))
dbus.exceptions.UnknownMethodException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method: getLogoActive is not a valid method of interface razer.device.lighting.logo

Failed to set/change brightness for Razer Blade Stealth (Late 2016).
Exception: org.freedesktop.DBus.Error.UnknownMethod: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 654, in _message_cb
    (candidate_method, parent_method) = _method_lookup(self, method_name, interface_name)
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 246, in _method_lookup
    raise UnknownMethodException('%s is not a valid method of interface %s' % (method_name, dbus_interface))
dbus.exceptions.UnknownMethodException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method: getLogoActive is not a valid method of interface razer.device.lighting.logo
```

**Comment by xlinbsd** [comment] 2017-07-19 09:06
The new capabilities
```
# Device Info
Name: Razer Blade Stealth (Late 2016)
Type: keyboard
 
# Device Capabilities
{'lighting_led_matrix': True, 'lighting_spectrum': True, 'lighting_ripple_random': True, 'lighting_pulsate': False, 'lighting_static': True, 'macro_tartarus_mode_modifier': False, 'serial': True, 'lighting_breath_random': True, 'lighting_scroll_breath_dual': False, 'lighting_scroll_active': False, 'name': True, 'brightness': True, 'lighting_breath_triple': False, 'lighting_logo_none': False, 'lighting_logo_blinking': False, 'lighting_scroll_breath_single': False, 'lighting_reactive': True, 'lighting_backlight_active': False, 'lighting_logo_breath_random': False, 'type': True, 'lighting_ripple': True, 'macro_mode_led_effect': False, 'lighting_scroll_reactive': False, 'lighting_logo_spectrum': False, 'lighting': True, 'lighting_logo_brightness': False, 'lighting_scroll_breath_random': False, 'lighting_led_single': False, 'lighting_logo': True, 'game_mode_led': False, 'lighting_logo_static': False, 'firmware_version': True, 'lighting_scroll_static': False, 'macro_logic': False, 'lighting_scroll_spectrum': False, 'lighting_scroll_pulsate': False, 'lighting_wave': True, 'lighting_scroll_brightness': False, 'lighting_backlight': False, 'lighting_scroll': False, 'lighting_scroll_blinking': False, 'lighting_logo_breath_dual': False, 'lighting_logo_active': True, 'lighting_none': True, 'lighting_scroll_none': False, 'lighting_breath_dual': True, 'macro_mode_led': False, 'lighting_logo_reactive': False, 'lighting_logo_breath_single': False, 'lighting_breath_single': True, 'lighting_logo_pulsate': False}
```

**Comment by ahmadnassri** [comment] 2017-07-22 23:19
:+1: same issue here, followed the patched `.py` file and ended up with the same result, happy to test further patches.

**Comment by lah7** [comment] 2017-07-23 10:09
Sorry, I should've replied sooner but I'm not sure which is at fault -- the daemon (via DBus) or Polychromatic's logic.

---------

To isolate this, please could you install the latest packaged driver/daemon. If you're on Ubuntu, you can use this (new) daily PPA and restart the daemon:

```
sudo add-apt-repository ppa:openrazer/daily
sudo apt update
sudo apt upgrade
```

It's probably best to restart the system at this point so the latest driver is loaded and the daemon is restarted. Then, run these commands in `python3`:

```
import razer.client
a = razer.client.DeviceManager()
b = devices[0]                      // Change 0 to 1,2, etc if multiple devices on system
b.name                              // Should output "Razer Blade Stealth"
b.fx.misc.logo.active               // Should output 0 or 1,  or True or False
b.fx.misc.logo.active = True        // Should turn the logo on
b.fx.misc.logo.active = 1           // Or it might be this?
```

If a `dbus.exceptions.UnknownMethodException` happens here, that concludes it's an issue at the daemon level. Otherwise, if there's no error, please let me know which command worked.

I'm betting the other options disappeared because of that exception. I'll add checks to prevent that from happening.

**Comment by xlinbsd** [comment] 2017-07-23 12:42
No attribute found

```
>>> b.name
'Razer Blade Stealth (Late 2016)'
>>> b.fx.misc.logo.active = True
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'active'
>>> b.fx.misc
<razer.client.fx.MiscLighting object at 0x7ff79be03f98>
>>> b.fx.misc.logo
>>> b.fx.misc.__dict__
{'_lighting_dbus': <Interface <ProxyObject wrapping <dbus._dbus.SessionBus (session) at 0x7ff7a33edf68> :1.61 /org/razer/device/BY1641A28000456 at 0x7ff79cacd6d8> implementing 'razer.device.lighting.logo' at 0x7ff79be03d68>, '_dbus': <ProxyObject wrapping <dbus._dbus.SessionBus (session) at 0x7ff7a33edf68> :1.61 /org/razer/device/BY1641A28000456 at 0x7ff79cacd6d8>, '_capabilities': {'lighting_led_matrix': True, 'lighting_breath_random': True, 'lighting_ripple_random': True, 'lighting_scroll_none': False, 'lighting_logo_brightness': False, 'lighting_starlight_single': False, 'lighting_wave': True, 'macro_logic': False, 'macro_mode_led_effect': False, 'lighting_pulsate': False, 'lighting_led_single': False, 'lighting_logo_reactive': False, 'lighting_scroll': False, 'lighting_scroll_breath_dual': False, 'brightness': True, 'lighting_starlight_dual': False, 'lighting_breath_triple': False, 'lighting_breath_dual': True, 'lighting_logo_active': False, 'lighting_none': True, 'lighting': True, 'lighting_breath_single': True, 'lighting_logo_breath_dual': False, 'lighting_ripple': True, 'game_mode_led': False, 'lighting_backlight_active': False, 'lighting_reactive': True, 'name': True, 'lighting_scroll_breath_random': False, 'firmware_version': True, 'lighting_backlight': False, 'lighting_logo_breath_random': False, 'lighting_scroll_blinking': False, 'lighting_logo_none': False, 'type': True, 'lighting_logo_spectrum': False, 'macro_mode_led': False, 'lighting_static': True, 'lighting_starlight_random': False, 'lighting_scroll_spectrum': False, 'lighting_scroll_pulsate': False, 'lighting_scroll_active': False, 'lighting_scroll_brightness': False, 'lighting_logo_breath_single': False, 'macro_tartarus_mode_modifier': False, 'lighting_logo_blinking': False, 'lighting_logo_static': False, 'lighting_scroll_reactive': False, 'lighting_logo': False, 'lighting_scroll_static': False, 'lighting_spectrum': True, 'lighting_scroll_breath_single': False, 'serial': True, 'lighting_logo_pulsate': False}, '_backlight': None, '_logo': None, '_scroll': None}
>>> b.fx.misc.logo.__dict__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute '__dict__'
```

**Comment by xlinbsd** [comment] 2017-07-26 14:54
Please notice I updated the above report.

**Comment by lah7** [comment] 2017-07-30 15:43
@terrycain committed a fix, it was missing some daemon stuff, but _should_ in theory work now.

https://github.com/terrycain/razer-drivers/commit/cccc4fcba10e0b700ea85524a1e59f73b484f130

A new daemon version was just released, please do give `v1.1.15` a test when the packages are available.

**Comment by lah7** [comment] 2017-08-04 21:00
Please could someone with a `Razer Blade Stealth (Late 2016)` confirm if works since the last daemon update?

I believe there should be a brightness slider (for keyboard) and a logo toggle. Is this the case?

**Comment by xlinbsd** [comment] 2017-08-07 15:51
Sorry for the delay.
Tried today with daemon update 1.1.15, no logo toggle.

**Closed** 2017-09-01 21:11 UTC
Labels: bug, daemon related, device support

**Comment by TheodoreT** [comment] 2020-01-07 20:32
@lah7 I am not sure whether I am get it right or not but is it possible to toggle on/off the razer logo on the lid of a blade by using polychromatic because at least I do not see any option for that.

**Comment by lah7** [comment] 2020-01-07 21:07
I don't have the hardware to check, but according to the "OpenRazer fake driver". I can see the logo toggle for:

* Blade Stealth
* Blade Stealth [Mid 2017]
* Blade Stealth [Late 2016]
* Blade QHD
* Blade Pro [Late 2016]

The **Blade [Late 2016]** and **Blade [Pro 2017]** apparently doesn't have this option.

![image](https://user-images.githubusercontent.com/13032135/71929422-7d464e80-3191-11ea-8d4e-92a671f04f4a.png)

This toggle appears if OpenRazer have the capabilities `lighting_logo` and `lighting_logo_active` enabled for your specific Blade model.

**Comment by TheodoreT** [comment] 2020-01-07 21:25
In my case I have the advanced mid '19 model with the oled monitor and it does not show up:

![image](https://user-images.githubusercontent.com/10189018/71930109-e8445500-3192-11ea-958e-f715c95fdaa3.png)

which is also confirmed from the output of the `polychromatic-controller --print-device-info` command:

```
-------------------------------------------------------------------------------
```
# Device Info
Name: Razer Blade 15 (Mid 2019) Mercury White
Type: keyboard
 
# Device Capabilities
{'name': True, 'type': True, 'firmware_version': True, 'serial': True, 'brightness': True, 'macro_logic': False, 'keyboard_layout': True, 'lighting': True, 'lighting_breath_single': True, 'lighting_breath_dual': True, 'lighting_breath_triple': False, 'lighting_breath_random': True, 'lighting_wave': True, 'lighting_reactive': True, 'lighting_none': True, 'lighting_spectrum': True, 'lighting_static': True, 'lighting_starlight_single': True, 'lighting_starlight_dual': True, 'lighting_starlight_random': True, 'lighting_ripple': True, 'lighting_ripple_random': True, 'lighting_pulsate': False, 'lighting_led_matrix': True, 'lighting_led_single': False, 'lighting_logo': False, 'lighting_logo_active': False, 'lighting_logo_blinking': False, 'lighting_logo_brightness': False, 'lighting_logo_pulsate': False, 'lighting_logo_spectrum': False, 'lighting_logo_static': False, 'lighting_logo_none': False, 'lighting_logo_reactive': False, 'lighting_logo_wave': False, 'lighting_logo_breath_single': False, 'lighting_logo_breath_dual': False, 'lighting_logo_breath_random': False, 'lighting_scroll': False, 'lighting_scroll_active': False, 'lighting_scroll_blinking': False, 'lighting_scroll_brightness': False, 'lighting_scroll_pulsate': False, 'lighting_scroll_spectrum': False, 'lighting_scroll_static': False, 'lighting_scroll_none': False, 'lighting_scroll_reactive': False, 'lighting_scroll_wave': False, 'lighting_scroll_breath_single': False, 'lighting_scroll_breath_dual': False, 'lighting_scroll_breath_random': False, 'lighting_left': False, 'lighting_left_active': False, 'lighting_left_brightness': False, 'lighting_left_spectrum': False, 'lighting_left_static': False, 'lighting_left_none': False, 'lighting_left_reactive': False, 'lighting_left_wave': False, 'lighting_left_breath_single': False, 'lighting_left_breath_dual': False, 'lighting_left_breath_random': False, 'lighting_right': False, 'lighting_right_active': False, 'lighting_right_brightness': False, 'lighting_right_spectrum': False, 'lighting_right_static': False, 'lighting_right_none': False, 'lighting_right_reactive': False, 'lighting_right_wave': False, 'lighting_right_breath_single': False, 'lighting_right_breath_dual': False, 'lighting_right_breath_random': False, 'lighting_backlight': False, 'lighting_backlight_active': False, 'game_mode_led': False, 'macro_mode_led': False, 'macro_mode_led_effect': False, 'macro_mode_modifier': False}
```
-------------------------------------------------------------------------------
```

which I guess means that OpenRazer does not support it yet as you said since `lighting_logo` and `lighting_logo_active` are set to `false`. 

Should I open an issue at the OpenRazer reporitory, or do you know if @terrycain is already aware of it?

**Comment by lah7** [comment] 2020-01-07 21:40
Please do open an issue on the OpenRazer repository.

If you're lucky, you might just need `get_logo_active` and `set_logo_active` adding here:

https://github.com/openrazer/openrazer/blob/8ec0f649d6e5081d70cce58e6eeb64f3a85605da/daemon/openrazer_daemon/hardware/keyboards.py#L1191-L1207

You could edit this on your system to try (as root) - the path is either:

*  `/usr/lib/python3/dist-packages/openrazer_daemon/hardware/keyboards.py` 
* **or** ``/usr/lib/python3.8/site-packages/openrazer_daemon/hardware/keyboards.py``

Then run `openrazer-daemon -r` to reload and restart Polychromatic.

Although, there's a chance it won't work on your particular model if the driver/firmware doesn't support it.

**Comment by TheodoreT** [comment] 2020-01-07 22:05
I tried what you have suggested, and while it shows up the menu for toggling the logo it causes two other issues:

1. it fails to communicate with the daemon for this device:
![image](https://user-images.githubusercontent.com/10189018/71932951-e41b3600-3198-11ea-96f4-c796ecb4177f.png)

2. it is failing to toggle the logo:
![image](https://user-images.githubusercontent.com/10189018/71933096-3b210b00-3199-11ea-952f-1ee998c41bc1.png)

Anyways, I will create an new issue on the OpenRazer repository.

Thanks a lot for your time :-).

**Comment by lah7** [comment] 2020-01-21 14:42
I noticed success in https://github.com/openrazer/openrazer/issues/992 by adding a condition for your device in the driver. :+1:

To reveal more of this "failed to set" error, run `polychromatic-controller` in the terminal. This will show (in this version) the last line of a stack trace, which should give us a clue.

---
**Slight related:** I recently discovered a bug where the Controller isn't showing all the effects/brightness options for Blade laptops. This app version's logic is old and doesn't handle this "logo brightness" option very well. See https://github.com/polychromatic/polychromatic/issues/229 if you wish to patch this in the interim until the next version supersedes.

**Comment by TheodoreT** [comment] 2020-01-21 23:50
@lah7 thanks for the feedback. After adding the condition for toggling the logo for my device in the driver I am not getting anymore the "failed to set" errors. 

However, it seems that I am also affected from the bug that isn't showing all the effects/brightness options. if I find some time I will try to add the patch or wait until it reaches upstream.
