### ISSUE TITLE
Tray-applet sub-menus going off-screen

### ISSUE THREAD

**Issue by ebelsx7** [lah7/polychromatic#97] opened 2017-06-15 20:44 UTC
The tray-applet sub-menus are going off-screen a lot of the times.
Mostly happens at the first time hovering, but not always.
The first hover displays the menu to the right going off-screen, everytime afterwards it's displayed accordingly.

Can reproduce it everytime just have to restart the tray-applet to reset it to the 'first hover goes off-screen' status.

Using the latest AUR version on manjaro with KDE.
If it helps, occured on 1366x768 resolution.

gif showing the bug:

![tray icon bug](https://user-images.githubusercontent.com/22804586/27200622-ba479e5a-521a-11e7-98ba-5bf95d9822e9.gif)

**Comment by BlauerHunger** [comment] 2017-06-16 08:50
I'm experiencing this issue, too.

**Comment by lah7** [comment] 2017-06-17 10:42
Unfortunately, I don't think this is something that can be fixed on Polychromatic's end. It looks like some sort of KDE bug.

Does this happen with other GTK applications?

If so, consider reporting to this to the KDE devs (https://bugs.kde.org/), especially if this just started happening in the latest version of KDE.

**Comment by ebelsx7** [comment] 2017-06-18 11:47
It never happened on another application to me so far.
and only started using polychromatic since a few days so can't tell abouth older versions of KDE.

If that's the case maybe I'll fill out a bugreport on the kde bugtracker if I can't find another open thread about it.

so should this issue be closed?:)

**Comment by lah7** [comment] 2017-06-18 20:55
The issue can be closed, since it's a KDE-specific issue. The info on replicating it from @BlauerHunger is certainly useful for them in reproducing the bug.

If you do find/open a bug report please do post a link back here. :+1:

**Closed by lah7** 2017-06-18 20:55 UTC
Labels: bug, desktop environment specific
