### ISSUE TITLE
polychromatic-controller, polychromatic-tray-applet crash on RBS

### ISSUE THREAD

**Issue by pjdaborowski** [lah7/polychromatic#31] opened 2016-09-25 11:32 UTC
razerkbd module is running 
attempt to run polychromatic-controller results in this error:
```
admin@laptop:~$ polychromatic-controller 
Using relative path for translations.
Traceback (most recent call last):
  File "/usr/bin/polychromatic-controller", line 1380, in <module>
    app = Controller()
  File "/usr/bin/polychromatic-controller", line 190, in __init__
    self.devman = rclient.DeviceManager()
  File "/usr/lib/python3/dist-packages/razer/client/__init__.py", line 33, in __init__
    device = _RazerDeviceFactory.get_device(serial)
  File "/usr/lib/python3/dist-packages/razer/client/device.py", line 56, in get_device
    device = device_class.get_device(serial, vid_pid=device_vid_pid, daemon_dbus=daemon_dbus)
  File "/usr/lib/python3/dist-packages/razer/client/devices/keyboard.py", line 148, in get_device
    return device_class(serial, vid_pid=vid_pid, daemon_dbus=daemon_dbus)
  File "/usr/lib/python3/dist-packages/razer/client/devices/keyboard.py", line 128, in __init__
    self._update_capabilities(default_capabilities)
AttributeError: 'RazerBladeStealthKeyboard' object has no attribute '_update_capabilities'`
```

**Comment by lah7** [comment] 2016-09-25 11:36
Duplicate of https://github.com/lah7/polychromatic/issues/30#issuecomment-249388472, it's a daemon bug with the Razer Blade Stealth.

There should be a new release of the daemon in the next day or so that will fix this.

**Closed by lah7** 2016-09-25 11:36 UTC
Labels: daemon related, duplicate
